language: r
sudo: false
cache: packages

matrix:
  include:
   - r: 3.2
   - r: 3.3
   - r: 3.4
   - r: 3.5
   - r: release
     before_cache: Rscript -e 'remotes::install_github("r-lib/pkgdown")'
     deploy:
       provider: script
       script: Rscript -e 'pkgdown::deploy_site_github(run_dont_run = TRUE)'
       skip_cleanup: true
   - r: devel

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'
